#!/bin/bash
S1='build'
S2='goat'
S3='AR'
S4='sum'
S5='butanol'
S6='carbon'
args=("$@")
S7='pi0'
S8='compton'
echo "now lets take care of "$1"ing for you, your Magesty.............................."
    #if [ "${args[$i]}" = "$S1" ];then
if [ "$1" = "$S1" ];then
    cd build/
    make -j4
    cd ../
fi  
if [ "$1" = "$S2" ];then
    #./build/bin/goat -d /media/external/output/ -D ~/analysis/1st_step -p Acqu_CBTaggTAPS -P GoATTrees configfiles/GoAT-Pi0.dat 
    #./build/bin/goat -f ~/output/Acqu_CBTaggTAPS_3681.root -D ~/analysis/1st_step -p Acqu_CBTaggTAPS -P GoATTrees configfiles/GoAT-Pi0.dat
    echo "kashti maaro?"
fi 
if [ "$1" = "$S3" ];then
    #./build/bin/AR_Class  -d ~/analaysis/1st_step -p GoATTrees -P MainGoAT -D ~/analysis/2nd_step configfiles/Physics-Pi0.dat
    #./build/bin/AR_Class  -f /home/al/analysis/1st_step/GoATTrees_3410.root -P MainGoAT -D /home/al/analysis/3rd_step configfiles/Physics-Pi0.dat
    echo "kooshi paa?"
fi  
if [ "$1" = "$S4" ];then
	if [ "$2" = "$S5" ];then
		if [ "$3" = "$S7"];then
		    	cd /home/al/analysis/2nd_step/oneH/
    			$ROOTSYS/bin/hadd MainGoAT_oneH.root *.root
			#ls /home/al/analysis/1st_step/"$2"/
  			mv MainGoAT_oneH.root /home/al/analysis/a2GoAT/
			cd /home/al/analysis/2nd_step/zeroH/
        	        $ROOTSYS/bin/hadd MainGoAT_zeroH.root *.root
			 mv MainGoAT_zeroH.root /home/al/analysis/a2GoAT/
		elif [ "$3" = "$S8" ];then 
			 cd /home/al/analysis/compton/2nd_step/oneH/
    			$ROOTSYS/bin/hadd MainGoAT_comp_oneH.root *.root
			#ls /home/al/analysis/1st_step/"$2"/
  			mv MainGoAT_comp_oneH.root /home/al/analysis/a2GoAT/
			cd /home/al/analysis/compton/2nd_step/zeroH/
        	        $ROOTSYS/bin/hadd MainGoAT_comp_zeroH.root *.root
	    		 mv MainGoAT_comp_zeroH.root /home/al/analysis/a2GoAT/
        	fi	
	
	elif [ "$2" = "$S6" ];then
		if [ "$3" = "$S7" ];then
	                cd /home/al/analysis/2nd_step/archive/
	                $ROOTSYS/bin/hadd MainGoAT_carbon.root *.root
	                mv MainGoAT_carbon.root /home/al/analysis/TestEnv/"$4"
		elif [ "$3" = "$S8" ];then
			cd /home/al/analysis/compton/2nd_step/archive/
	                $ROOTSYS/bin/hadd MainGoAT_comp_carbon.root *.root
	                mv MainGoAT_comp_carbon.root /home/al/analysis/TestEnv/"$4"
		fi
	fi
fi  
    


#./build/bin/goat -d /media/external/output/ -D ~/analysis/1st_step -p Acqu_CBTaggTAPS -P GoATTrees configfiles/GoAT-Pi0.dat 
#./build/bin/goat -f ~/output/Acqu_CBTaggTAPS_3681.root -D ~/analysis/1st_step -p Acqu_CBTaggTAPS -P GoATTrees configfiles/GoAT-Pi0.dat 
#./build/bin/AR_Class  -d ~/analaysis/1st_step -p GoATTrees -P MainGoAT -D ~/analysis/2nd_step configfiles/Physics-Pi0.dat
#./build/bin/AR_Class  -f /home/al/analysis/1st_step/GoATTrees_3410.root -P MainGoAT -D /home/al/analysis/3rd_step configfiles/Physics-Pi0.dat

#cd /home/al/analysis/2nd_step

#$ROOTSYS/bin/hadd Carbon_MainGoAT.root *.root
#MainGoAT_3680.root MainGoAT_3681.root MainGoAT_3683.root MainGoAT_3684.root MainGoAT_3685.root 
#MainGoAT_3699.root MainGoAT_3692.root MainGoAT_3694.root MainGoAT_3684.root MainGoAT_3683.root MainGoAT_3697.root MainGoAT_3696.root MainGoAT_3695.root MainGoAT_3685.root MainGoAT_3681.root MainGoAT_3691.root
